# This file contains values from Cookiecutter

default_context:
  project_name: "farcaster"
  project_description: "farcaster is a Python  SDK for the Farcaster Protocol"
  organization: "Mason Hall"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "fmhall"
  email: "masonhall@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
